<a href="https://colab.research.google.com/github/ojdunfee/ML/blob/main/sklearn_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preprocessing
* used to change raw feacture vectors into representation that is more suitable for downstream estimators.

In [1]:
from sklearn import preprocessing
import numpy as np

## Standardization, or mean removal and variance scaling
* Standardization: a common requirement for many machine learning estimators implemented in sklearn.
* Often ignore the shape of the distribution and just transform the data to center it by removing the mean value of each feature, then scale it by dividing non-constant features by their standard deviation.
* many elements used in the objective function of a learning algorithm assume that all features are centered around zero and have variance in the same order.

### StandardScaler()
* a quick easy way to perform the following operation on an array-like dataset

In [2]:
X_train = np.array([[1., -1., 2.],
                    [2., 0., 0.],
                    [0., 1., -1.]])
scaler = preprocessing.StandardScaler().fit(X_train)
print('X_train')
print(X_train)
print()
print('scaler.mean_:')
print(scaler.mean_)
print()
print('scaler.scale_')
print(scaler.scale_)
print()
X_scaled = scaler.transform(X_train)
print('scaler.transform(X_train)')
print(X_scaled)
print()
print('X_scaled.mean(axis=0)')
print(X_scaled.mean(axis=0))
print()
print('(X_scaled.std(axis=0)')
print(X_scaled.std(axis=0))

X_train
[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]

scaler.mean_:
[1.         0.         0.33333333]

scaler.scale_
[0.81649658 0.81649658 1.24721913]

scaler.transform(X_train)
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]

X_scaled.mean(axis=0)
[0. 0. 0.]

(X_scaled.std(axis=0)
[1. 1. 1.]


In [3]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

X, y = make_classification(random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(X_train, y_train)
print(pipe.score(X_test, y_test))

0.96


## Scaling features to a range
* An alternative standardization is scaling features to lie between a given min and max value using MinMaxScaler() or MaxAbsScaler()
* The motivation to use this scaling include robustness to very small standard deviations of features and preserving zero entries in sparse data.

In [4]:
X_train = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])

min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
print(X_train_minmax)

[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]


In [5]:
X_test = np.array([[-3., -1., 4.]])
X_test_minmax = min_max_scaler.transform(X_test)
print(X_test_minmax)

[[-1.5         0.          1.66666667]]


In [6]:
print(min_max_scaler.scale_)
print()
print(min_max_scaler.min_)

[0.5        0.5        0.33333333]

[0.         0.5        0.33333333]


### MaxAbsScaler()
* works in a very similar fashion, but scales in a way that the training data lies within the range [-1, 1] by dividing through the largest maximum value in each feature.
* meant for data that is already centered at zero or sparse data.

In [7]:
X_train = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])

max_abs_scaler = preprocessing.MaxAbsScaler()
X_train_maxabs = max_abs_scaler.fit_transform(X_train)
print(X_train_maxabs)
print()
X_test = np.array([[-3., -1., 4.]])
X_test_maxabs = max_abs_scaler.transform(X_test)
print(X_test_maxabs)
print()
print(max_abs_scaler.scale_)

[[ 0.5 -1.   1. ]
 [ 1.   0.   0. ]
 [ 0.   1.  -0.5]]

[[-1.5 -1.   2. ]]

[2. 1. 2.]


## Mapping to a Uniform distribution
* QuantileTransformer(): provides a non-parametric transformation to map the data to a uniform distribution with values between 0 and 1:

In [8]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
quantile_transformer = preprocessing.QuantileTransformer(random_state=0)
X_train_trans = quantile_transformer.fit_transform(X_train)
X_test_trans = quantile_transformer.fit_transform(X_test)
np.percentile(X_train[:, 0], [0, 25, 50, 75, 100])

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (112). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (38). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)


array([4.3, 5.1, 5.8, 6.5, 7.9])

In [9]:
np.percentile(X_train_trans[:, 0], [0, 25, 50, 75, 100])

array([0.        , 0.23873874, 0.50900901, 0.74324324, 1.        ])

In [10]:
np.percentile(X_test[:, 0], [0, 25, 50, 75, 100])

array([4.4  , 5.125, 5.75 , 6.175, 7.3  ])

In [11]:
np.percentile(X_test_trans[:, 0], [0, 25, 50, 75, 100])

array([0.        , 0.25337838, 0.5       , 0.74324324, 1.        ])

## Mapping to a Gaussian distribution
* when normality of the features in a dataset is desirable. Power transforms are a family of parametrics, monotonic transformations that aim to map data from any distribution to as close to a Gaussian distribution as possible in order to stabilize variance and minimize skewness.
* options are Yeo-Johnson and Box-Cox
* Box-Cox can only be applied to strictly positive data.

In [12]:
pt = preprocessing.PowerTransformer(method='box-cox', standardize=False)
X_lognormal = np.random.RandomState(616).lognormal(size=(3, 3))
print(X_lognormal)
print()
print(pt.fit_transform(X_lognormal))

[[1.28331718 1.18092228 0.84160269]
 [0.94293279 1.60960836 0.3879099 ]
 [1.35235668 0.21715673 1.09977091]]

[[ 0.49024349  0.17881995 -0.1563781 ]
 [-0.05102892  0.58863195 -0.57612415]
 [ 0.69420009 -0.84857822  0.10051454]]


In [13]:
quantile_transformer = preprocessing.QuantileTransformer(
    output_distribution='normal', random_state=0
)
X_trans = quantile_transformer.fit_transform(X)
print(quantile_transformer.quantiles_)

[[4.3 2.  1.  0.1]
 [4.4 2.2 1.1 0.1]
 [4.4 2.2 1.2 0.1]
 [4.4 2.2 1.2 0.1]
 [4.5 2.3 1.3 0.1]
 [4.6 2.3 1.3 0.2]
 [4.6 2.3 1.3 0.2]
 [4.6 2.3 1.3 0.2]
 [4.6 2.4 1.3 0.2]
 [4.7 2.4 1.3 0.2]
 [4.7 2.4 1.3 0.2]
 [4.8 2.5 1.4 0.2]
 [4.8 2.5 1.4 0.2]
 [4.8 2.5 1.4 0.2]
 [4.8 2.5 1.4 0.2]
 [4.8 2.5 1.4 0.2]
 [4.9 2.5 1.4 0.2]
 [4.9 2.5 1.4 0.2]
 [4.9 2.5 1.4 0.2]
 [4.9 2.6 1.4 0.2]
 [4.9 2.6 1.4 0.2]
 [4.9 2.6 1.4 0.2]
 [5.  2.6 1.4 0.2]
 [5.  2.6 1.4 0.2]
 [5.  2.7 1.5 0.2]
 [5.  2.7 1.5 0.2]
 [5.  2.7 1.5 0.2]
 [5.  2.7 1.5 0.2]
 [5.  2.7 1.5 0.2]
 [5.  2.7 1.5 0.2]
 [5.  2.7 1.5 0.2]
 [5.  2.7 1.5 0.2]
 [5.1 2.7 1.5 0.2]
 [5.1 2.8 1.5 0.2]
 [5.1 2.8 1.5 0.3]
 [5.1 2.8 1.5 0.3]
 [5.1 2.8 1.5 0.3]
 [5.1 2.8 1.6 0.3]
 [5.1 2.8 1.6 0.3]
 [5.1 2.8 1.6 0.3]
 [5.1 2.8 1.6 0.3]
 [5.2 2.8 1.6 0.4]
 [5.2 2.8 1.6 0.4]
 [5.2 2.8 1.6 0.4]
 [5.2 2.8 1.7 0.4]
 [5.3 2.8 1.7 0.4]
 [5.4 2.8 1.7 0.4]
 [5.4 2.9 1.7 0.4]
 [5.4 2.9 1.9 0.5]
 [5.4 2.9 1.9 0.6]
 [5.4 2.9 3.  1. ]
 [5.4 2.9 3.3 1. ]
 [5.5 2.9 3.

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (150). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)


## Normalization
* the process of scaling individual samples to have unit norm.
* can be useful if you plan to use a quadratic form such as the dot-product or any other kernel to quantify the similarity of any pair of samples.
* often used in text classification and clustering contexts.

In [14]:
X = [[ 1., -1.,  2.],
      [ 2.,  0.,  0.],
      [ 0.,  1., -1.]]
X_normalized = preprocessing.normalize(X, norm='l2')
print(X_normalized)

[[ 0.40824829 -0.40824829  0.81649658]
 [ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]]


## Encoding categorical features
* to convert categorical features to such integer codes, we use the OrdinalEncoder()
* will passthrough missing values

In [15]:
enc = preprocessing.OrdinalEncoder()
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)
print(enc.transform([['female', 'from US', 'uses Safari']]))

[[0. 1. 1.]]


In [16]:
enc = preprocessing.OrdinalEncoder()
X = [['male'], ['female'], [np.nan], ['female']]
print(enc.fit_transform(X))

[[ 1.]
 [ 0.]
 [nan]
 [ 0.]]


Another possibility to convert categorical features to features that can be used with scikit-learn estimators is to use a one-of-K, also known as one-hot or dummy encoding. This type of encoding can be obtained with the OneHotEncoder, which transforms each categorical feature with n_categories possible values into n_categories binary features, with one of them 1, and all others 0.

In [17]:
enc = preprocessing.OneHotEncoder()
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)
print(enc.transform([['female','from US','uses Safari'],
                     ['male', 'from Europe', 'uses Safari']]).toarray())
print()
print(enc.categories_)

[[1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 0. 0. 1.]]

[array(['female', 'male'], dtype=object), array(['from Europe', 'from US'], dtype=object), array(['uses Firefox', 'uses Safari'], dtype=object)]


In [18]:
genders = ['female','male']
locations = ['from Africa', 'from Asia', 'from Europe', 'from US']
browsers = ['uses Chrome', 'uses Firefox', 'uses IE', 'uses Safari']
enc = preprocessing.OneHotEncoder(categories=[genders, locations, browsers])
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)
print(enc.transform([['female','from Asia','uses Chrome']]).toarray())


[[1. 0. 0. 1. 0. 0. 1. 0. 0. 0.]]


## Discretization
* also quantization or binning, provides a way to partition continuous features into discrete values.
* can transform the dataset of continuous attributes to one with only nominal attributes.
* Discretization is similar to constructing histograms for continuous data. However, histograms focus on counting features which fall into particular bins, whereas discretization focuses on assigning feature values to these bins.

In [19]:
X = np.array([[ -3., 5., 15 ],
               [  0., 6., 14 ],
               [  6., 3., 11 ]])
est = preprocessing.KBinsDiscretizer(n_bins=[3, 2, 2], encode='ordinal').fit(X)

In [20]:
est.transform(X)

array([[0., 1., 1.],
       [1., 1., 1.],
       [2., 0., 0.]])

In [21]:
import pandas as pd
import numpy as np
bins = [0, 1, 13, 20, 60, np.inf]
labels = ['infant','kid','teen','adult','senior citizen']
transformer = preprocessing.FunctionTransformer(
    pd.cut, kw_args={'bins':bins, 'labels':labels, 'retbins': False}
)
X = np.array([0.2, 2, 15, 25, 97])
transformer.fit_transform(X)

['infant', 'kid', 'teen', 'adult', 'senior citizen']
Categories (5, object): ['infant' < 'kid' < 'teen' < 'adult' < 'senior citizen']

## Feature binarization
* The process of thresholding numerical features to get boolean values.
* useful for downstream probabilistic estimators that make assumption that the input data is distributed according to a multi-variate Bernoulli distribution.
* common among the text processing community to use binary feature values but TF-IDF perform slightly better.

In [22]:
X = [[ 1., -1.,  2.],
      [ 2.,  0.,  0.],
      [ 0.,  1., -1.]]
binarizer = preprocessing.Binarizer().fit(X)
print(binarizer.transform(X))

[[1. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


It is possible to adjust the threshold of the binarizer:

In [23]:
binarizer = preprocessing.Binarizer(threshold=1.1)
binarizer.transform(X)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])

# Imputation of missing values

## Univariate vs. Multivariate Imputation
* univariate imputes values in the i-th feature dimension using only non-missing values in that feature dimension
* multivariate use the entire set of available feature dimensions to estimate the missing values

### Univariate feature imputation
* SimpleImputer(): basic strategies for imputing missing values.
* missing values can be imputed with a provided constant value, or using the statistics (mean, median, most frequent) of each column in which the missing values are located.
* also allows for different missing values encodings.

In [25]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit([[1,2], [np.nan, 3], [7, 6]])
X = [[np.nan, 2], [np.nan, 3], [7, 6]]
print(imp.transform(X))

3.0


Also supports sparse matrices

In [26]:
import scipy.sparse as sp
X = sp.csc_matrix([[1,2], [0,-1], [8,4]])
imp = SimpleImputer(missing_values=-1, strategy='mean')
imp.fit(X)
X_test = sp.csc_matrix([[-1,2],[6,-1],[7,6]])
print(imp.transform(X_test).toarray())

[[3. 2.]
 [6. 3.]
 [7. 6.]]


The SimpleImputer class also supports categorical data represented as string values or pandas categoricals when using the 'most_frequent' or 'constant' strategy:

In [27]:
import pandas as pd
df = pd.DataFrame([["a", "x"],
                   [np.nan, "y"],
                   ["a", np.nan],
                   ["b","y"]], dtype="category")

imp = SimpleImputer(strategy="most_frequent")
print(imp.fit_transform(df))

[['a' 'x']
 ['a' 'y']
 ['a' 'y']
 ['b' 'y']]


### Multivariate feature imputation
* IterativeImputer(): models each feature with missing values as a function of other features, and uses that estimate for imputation.
* uses an iterated round-robin fashion: at each step, a feature column is designated as output y and the other feature columns are treated as inputs X. A regressor is fit on (X, y) for known y. Then the regressor is used to predict the missing values of y.

In [28]:
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imp = IterativeImputer(max_iter=10, random_state=0)
imp.fit([[1,2],[3,6],[4,8],[np.nan,3],[7,np.nan]])
X_test = [[np.nan,2],[6,np.nan],[np.nan,6]]
print(np.round(imp.transform(X_test)))

[[ 1.  2.]
 [ 6. 12.]
 [ 3.  6.]]


### Nearest neighbors imputation
* KNNImputer(): provides imputation for missing values using the k-Nearest Neighbors approach.
* each missing feature is implemented using values from n_neighbors nearest neighbors that have a value for that feature.

In [29]:
import numpy as np
from sklearn.impute import KNNImputer
nan = np.nan
X = [[1, 2, nan], [3, 4, 3], [nan, 6, 5], [8, 8, 7]]
imputer = KNNImputer(n_neighbors=2, weights="uniform")
imputer.fit_transform(X)

array([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])

## Polynomial features
* useful to add complexity to a model by considering nonlinear features of the input data

In [31]:
import numpy as np
X = np.arange(6).reshape(3,2)
print(X)
print()
poly = preprocessing.PolynomialFeatures(2)
poly.fit_transform(X)

[[0 1]
 [2 3]
 [4 5]]



array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In some cases, only interaction terms among features are required, and it can be gotten with the setting interaction_only=True:

In [32]:
X = np.arange(9).reshape(3,3)
print(X)
print()
poly = preprocessing.PolynomialFeatures(degree=3, interaction_only=True)
poly.fit_transform(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]



array([[  1.,   0.,   1.,   2.,   0.,   0.,   2.,   0.],
       [  1.,   3.,   4.,   5.,  12.,  15.,  20.,  60.],
       [  1.,   6.,   7.,   8.,  42.,  48.,  56., 336.]])

## Custom transformers
* To convert an existing Python function into a transformer to assist in data cleaning or processing.
* implement a transformer from an arbitrary function with FunctionTransformer()
* Ex: build a transformer that applies a log transformation in a pipeline

In [33]:
import numpy as np
transformer = preprocessing.FunctionTransformer(np.log1p, validate=True)
X = np.array([[0, 1], [2, 3]])
transformer.transform(X)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

You can ensure that func and inverse_func are the inverse of each other by setting check_inverse=True and calling fit before transform. Please note that a warning is raised and can be turned into an error with a filterwarnings:

In [34]:
import warnings
warnings.filterwarnings("error", message=".*check_inverse*.",
                        category=UserWarning, append=False)